sudo: required
services:
    -docker

before_install:
    - docker build -t nogba/react-test -f ./client/Dockerfile.dev ./client
      
script:
    - docker run -e CI=true nogba/react-test npm test

after_success:
    - docker build -t nogba/multi-client ./client
    - docker build -t nogba/multi-nginx ./nginx
    - docker build -t nogba/multi-server ./server
    - docker build -t nogba/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push nogba/multi-client
    - docker push nogba/multi-nginx
    - docker push nogba/multi-server
    - docker push nogba/multi-worker
    
